[package]
name = "gfx-examples"
version = "0.2.0"

[[bin]]
name = "cube"
path = "src/cube/main.rs"

[[bin]]
name = "deferred"
path = "src/deferred/main.rs"

[[bin]]
name = "flowmap"
path = "src/flowmap/main.rs"

[[bin]]
name = "performance"
path = "src/performance/main.rs"

[[bin]]
name = "shadow"
path = "src/shadow/main.rs"

[[bin]]
name = "terrain"
path = "src/terrain/main.rs"

[[bin]]
name = "triangle"
path = "src/triangle/main.rs"

[dependencies]
env_logger = "*"
log = "*"
gfx_gl = "*"
rand = "*"
time = "*"
genmesh = "*"
noise = "*"
image = "*"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
version = "*"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
version = "*"

[dependencies.gfx_window_glutin]
git = "https://github.com/gfx-rs/gfx_window_glutin"
version = "*"

[dependencies.gfx_window_glfw]
git = "https://github.com/gfx-rs/gfx_window_glfw"
version = "*"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
version = "*"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"
version = "*"
