[package]
name = "gfx-examples"
version = "0.3.0"

[[bin]]
name = "cube"
path = "src/cube/main.rs"

[[bin]]
name = "deferred"
path = "src/deferred/main.rs"

[[bin]]
name = "flowmap"
path = "src/flowmap/main.rs"

[[bin]]
name = "performance"
path = "src/performance/main.rs"

[[bin]]
name = "shadow"
path = "src/shadow/main.rs"

[[bin]]
name = "terrain"
path = "src/terrain/main.rs"

[[bin]]
name = "triangle"
path = "src/triangle/main.rs"

[dependencies]
env_logger = "*"
log = "*"
cgmath = "*"
gfx_gl = "*"
gfx = "*"
gfx_window_glutin = "*"
gfx_window_glfw = "*"
glutin = "*"
glfw = "*"
rand = "*"
time = "*"
genmesh = "*"
noise = "*"
image = "*"
